import { Lawyer, Case } from "@/types";

export const mockLawyers: Lawyer[] = [
  {
    id: "1",
    firstName: "Marie",
    lastName: "Dubois",
    email: "marie.dubois@avocat.fr",
    phone: "+33 6 12 34 56 78",
    region: "Île-de-France",
    address: "15 Rue de la Paix, 75002 Paris",
    registrationDate: "2024-01-15",
    acceptedCases: 12,
    rejectedCases: 2,
    activeCases: 5,
  },
  {
    id: "2",
    firstName: "Pierre",
    lastName: "Martin",
    email: "pierre.martin@avocat.fr",
    phone: "+33 6 23 45 67 89",
    region: "Provence-Alpes-Côte d'Azur",
    address: "28 Avenue des Champs, 13001 Marseille",
    registrationDate: "2024-02-20",
    acceptedCases: 8,
    rejectedCases: 1,
    activeCases: 3,
  },
  {
    id: "3",
    firstName: "Sophie",
    lastName: "Bernard",
    email: "sophie.bernard@avocat.fr",
    phone: "+33 6 34 56 78 90",
    region: "Auvergne-Rhône-Alpes",
    address: "42 Cours Lafayette, 69003 Lyon",
    registrationDate: "2024-03-10",
    acceptedCases: 15,
    rejectedCases: 3,
    activeCases: 7,
  },
];

export const mockCases: Case[] = [
  {
    id: "1",
    caseNumber: "AFF-2024-001",
    title: "Litige commercial - Contrat non respecté",
    type: "civil",
    description: "Différend contractuel entre deux entreprises concernant la livraison de marchandises.",
    createdAt: "2024-10-01",
    courtDate: "2024-11-15",
    status: "assigned",
    assignedLawyerId: "1",
    assignedLawyerName: "Marie Dubois",
    notificationSent: true,
    notificationDate: "2024-10-01T10:30:00Z",
  },
  {
    id: "2",
    caseNumber: "AFF-2024-002",
    title: "Divorce amiable",
    type: "civil",
    description: "Procédure de divorce par consentement mutuel.",
    createdAt: "2024-10-05",
    courtDate: "2024-11-20",
    status: "accepted",
    assignedLawyerId: "2",
    assignedLawyerName: "Pierre Martin",
    notificationSent: true,
    notificationDate: "2024-10-05T14:20:00Z",
  },
  {
    id: "3",
    caseNumber: "AFF-2024-003",
    title: "Succession familiale complexe",
    type: "civil",
    description: "Règlement d'une succession avec plusieurs héritiers.",
    createdAt: "2024-10-08",
    courtDate: "2024-12-01",
    status: "pending",
  },
];
